"""
Report generation for interpretability investigations.

Generates shareable Markdown and HTML reports from any AnalysisResult
or WorkflowResult, with embedded visualizations and executive summaries.
"""

import base64
import io
import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from .results import AnalysisResult


def generate_report(
    results: Union[AnalysisResult, List[AnalysisResult]],
    title: str = "Interpretability Report",
    description: str = "",
    format: str = "markdown",
    include_plots: bool = True,
    include_json: bool = False,
) -> str:
    """
    Generate a report from one or more analysis results.

    Args:
        results: Single result or list of results
        title: Report title
        description: Optional description/context
        format: "markdown" or "html"
        include_plots: Include embedded visualizations (HTML only)
        include_json: Include raw JSON data in appendix

    Returns:
        Report string (Markdown or HTML)
    """
    if isinstance(results, AnalysisResult):
        results = [results]

    if format == "html":
        return _generate_html_report(results, title, description, include_plots, include_json)
    else:
        return _generate_markdown_report(results, title, description, include_json)


def _generate_markdown_report(
    results: List[AnalysisResult],
    title: str,
    description: str,
    include_json: bool,
) -> str:
    """Generate a Markdown report."""
    lines = [
        f"# {title}",
        "",
        f"*Generated by mlxterp on {time.strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
    ]

    if description:
        lines.extend([description, ""])

    lines.extend([
        "## Summary",
        "",
        f"This report contains {len(results)} analysis result(s).",
        "",
    ])

    for i, result in enumerate(results):
        section_title = result.result_type.replace("_", " ").title()
        lines.extend([
            f"## {i + 1}. {section_title}",
            "",
            f"**Summary:** {result.summary()}",
            "",
        ])

        # Metadata
        if result.metadata:
            lines.append("### Parameters")
            lines.append("")
            for key, value in result.metadata.items():
                lines.append(f"- **{key}**: {value}")
            lines.append("")

        # Type-specific content
        lines.extend(_format_result_markdown(result))
        lines.append("")

        # Workflow steps
        if hasattr(result, "steps") and result.steps:
            lines.append("### Steps")
            lines.append("")
            for step_name, step_result in result.steps:
                lines.append(f"#### {step_name}")
                if hasattr(step_result, "summary"):
                    lines.append(f"{step_result.summary()}")
                elif isinstance(step_result, dict):
                    for k, v in list(step_result.items())[:10]:
                        lines.append(f"- {k}: {v}")
                lines.append("")

        # Narrative
        if hasattr(result, "narrative") and result.narrative:
            lines.extend([
                "### Narrative",
                "",
                result.narrative,
                "",
            ])

    if include_json:
        lines.extend([
            "## Appendix: Raw Data",
            "",
            "```json",
        ])
        for result in results:
            lines.append(result.to_json())
        lines.extend(["```", ""])

    lines.extend([
        "---",
        "*Generated with [mlxterp](https://github.com/coairesearch/mlxterp)*",
    ])

    return "\n".join(lines)


def _format_result_markdown(result: AnalysisResult) -> List[str]:
    """Format type-specific result content for Markdown."""
    lines = []

    if result.result_type == "patching":
        if hasattr(result, "top_components"):
            top = result.top_components(k=10)
            if top:
                lines.append("### Top Components")
                lines.append("")
                lines.append("| Rank | Component | Effect |")
                lines.append("|------|-----------|--------|")
                for rank, (comp, effect) in enumerate(top, 1):
                    lines.append(f"| {rank} | Layer {comp} | {effect:.4f} |")
                lines.append("")

    elif result.result_type == "dla":
        if hasattr(result, "target_token_str"):
            lines.append(f"**Target token:** '{result.target_token_str}' (id={result.target_token})")
            lines.append("")

    elif result.result_type == "circuit":
        if hasattr(result, "nodes"):
            lines.append(f"**Nodes:** {len(result.nodes)}")
            lines.append(f"**Edges:** {len(result.edges)}")
            lines.append("")
            if result.nodes:
                lines.append("### Circuit Components")
                lines.append("")
                for node in result.nodes:
                    lines.append(f"- {node}")
                lines.append("")

    elif result.result_type == "generation":
        if hasattr(result, "text"):
            lines.append(f"**Generated text:** {result.text}")
            lines.append("")

    elif result.result_type == "conversation":
        if hasattr(result, "turns"):
            lines.append(f"**Turns:** {len(result.turns)}")
            lines.append("")

    return lines


def _generate_html_report(
    results: List[AnalysisResult],
    title: str,
    description: str,
    include_plots: bool,
    include_json: bool,
) -> str:
    """Generate an HTML report."""
    # Convert markdown to basic HTML
    md = _generate_markdown_report(results, title, description, include_json)

    # Simple Markdown-to-HTML conversion
    html_body = _md_to_html(md)

    # Try to generate plots
    plot_sections = ""
    if include_plots:
        for i, result in enumerate(results):
            try:
                fig = result.plot()
                buf = io.BytesIO()
                fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
                buf.seek(0)
                img_b64 = base64.b64encode(buf.read()).decode()
                plot_sections += f'<div class="plot"><img src="data:image/png;base64,{img_b64}" alt="Plot {i+1}"></div>\n'
                import matplotlib.pyplot as plt
                plt.close(fig)
            except (NotImplementedError, Exception):
                pass

    return f"""<!DOCTYPE html>
<html>
<head>
<title>{_html_escape(title)}</title>
<style>
body {{ font-family: system-ui, -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }}
h1 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
h2 {{ color: #16213e; margin-top: 2em; }}
h3 {{ color: #0f3460; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; font-weight: 600; }}
tr:nth-child(even) {{ background: #fafafa; }}
code {{ background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
pre {{ background: #f5f5f5; padding: 16px; border-radius: 8px; overflow-x: auto; }}
.plot {{ margin: 1em 0; text-align: center; }}
.plot img {{ max-width: 100%; border: 1px solid #e0e0e0; border-radius: 8px; }}
blockquote {{ border-left: 3px solid #0066cc; margin: 1em 0; padding: 0.5em 1em; background: #f8f9fa; }}
em {{ color: #666; }}
</style>
</head>
<body>
{html_body}
{plot_sections}
</body>
</html>"""


def _md_to_html(md: str) -> str:
    """Simple Markdown to HTML conversion."""
    import re
    lines = md.split("\n")
    html_lines = []
    in_code = False
    in_table = False

    for line in lines:
        if line.startswith("```"):
            if in_code:
                html_lines.append("</code></pre>")
                in_code = False
            else:
                html_lines.append("<pre><code>")
                in_code = True
            continue

        if in_code:
            html_lines.append(_html_escape(line))
            continue

        # Headers
        if line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("#### "):
            html_lines.append(f"<h4>{line[5:]}</h4>")
        elif line.startswith("| ") and "---" not in line:
            # Table row
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if not in_table:
                html_lines.append("<table>")
                tag = "th"
                in_table = True
            else:
                tag = "td"
            row = "".join(f"<{tag}>{c}</{tag}>" for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
        elif line.startswith("| ") and "---" in line:
            continue  # Skip table separator
        elif line.startswith("- "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.startswith("*") and line.endswith("*"):
            html_lines.append(f"<p><em>{line.strip('*')}</em></p>")
        elif line.strip() == "---":
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append("<hr>")
        elif line.strip() == "":
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append("")
        else:
            # Apply inline formatting
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            line = re.sub(r"`(.+?)`", r"<code>\1</code>", line)
            html_lines.append(f"<p>{line}</p>")

    if in_table:
        html_lines.append("</table>")

    return "\n".join(html_lines)


def _html_escape(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def save_report(
    results: Union[AnalysisResult, List[AnalysisResult]],
    path: str,
    title: str = "Interpretability Report",
    description: str = "",
    **kwargs,
) -> str:
    """
    Generate and save a report to a file.

    The format is auto-detected from the file extension (.md or .html).

    Args:
        results: Analysis result(s)
        path: Output file path
        title: Report title
        description: Optional description
        **kwargs: Passed to generate_report()

    Returns:
        Path to the saved file
    """
    path = Path(path)
    fmt = "html" if path.suffix == ".html" else "markdown"

    report = generate_report(
        results, title=title, description=description,
        format=fmt, **kwargs,
    )

    path.write_text(report)
    return str(path)
